[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[services]]
name = "patent-api"
port = 3005

[services.patent-api]
healthcheck = "/health"